### ISSUE TITLE
Can't work in ST3 unless commenting the 3 lines

### ISSUE THREAD

**Issue by liuhewei** [vprimachenko/Sublime-Colorcoder#36] opened 2014-11-05 01:20 UTC
When I use Colorcoder in ST3, Errors are reported:
Traceback (most recent call last):
  File "D:\Tools\Sublime Text\sublime_plugin.py", line 157, in on_api_ready
    m.plugin_loaded()
  File "D:\Tools\Sublime Text\Data\Packages\Colorcoder\colorcoder.py", line 238, in plugin_loaded
    colorshemeemodifier.maybefixscheme()
  File "D:\Tools\Sublime Text\Data\Packages\Colorcoder\colorcoder.py", line 160, in maybefixscheme
    colorshemeemodifier.modify_color_scheme(set.get('lightness'),set.get('saturation'))
  File "D:\Tools\Sublime Text\Data\Packages\Colorcoder\colorcoder.py", line 167, in modify_color_scheme
    if sublime.load_settings("Preferences.sublime-settings").get('original_color_scheme').find('/Colorcoder/') != -1:
AttributeError: 'NoneType' object has no attribute 'find'

So I comment the 3 lines here, then it's OK now:
https://github.com/vprimachenko/Sublime-Colorcoder/blob/master/colorcoder.py#L167-169

**Comment by vprimachenko** [comment] 2014-11-05 12:51
duplicate of #33

**Closed as completed by vprimachenko** 2014-11-05 12:51 UTC
