### ISSUE TITLE
How to get extension working?

### ISSUE THREAD

**Issue by jdlyga** [vprimachenko/Sublime-Colorcoder#1] opened 2014-02-11 15:46 UTC
I love the idea of this extension, but I can't get it to work in Sublime Text 2.  I'm testing this out viewing *.cpp and *.h files using the colorcoder color scheme, and it looks like normal Obsidian to me.  I installed the extension using package control.  Does it automatically start working or are there additional setup procedures?  Is there a comand that I need to run?  Do I need to copy over the modified c++ language files somewhere else?  Thanks!

**Comment by vprimachenko** [comment] 2014-02-11 18:44
indeed, it does seem not to work in sublime 2, i am looking into this

**Comment by vprimachenko** [comment] 2014-02-11 19:08
quick and dirty hack is to edit the plugin (i will make changes to the plugin in the repo soon)

```
@@ -47,2 +47,2 @@
-   def on_activated_async(self, view):
-       self.on_modified_async(view)
+   def on_activated(self, view):
+       self.on_modified(view)
@@ -50,1 +50,1 @@
-   def on_modified_async(self, view):
+   def on_modified(self, view):
@@ -59,1 +59,1 @@
-           view.add_regions('cc'+key,regs[key],'cc'+key,'', sublime.DRAW_NO_OUTLINE )
+           view.add_regions('cc'+key,regs[key],'cc'+key )
```

you also need to select `C++ (Colorcode)` as language

**Comment by vprimachenko** [comment] 2014-02-13 15:59
@jdlyga please confirm the issue is fixed in newest version

**Comment by jdlyga** [comment] 2014-02-13 19:11
@vprimachenko the latest version looks good to me in Sublime Text 2.02.  I didn't have to manually select the colorcoder c++ syntax highlighting since it simultaneously selects c++ and c++ colorcoder.  Thanks for the quick fix

**Comment by vprimachenko** [comment] 2014-02-14 14:56
you're welcome, tune in for updates and feel free to submit feature requests

**Closed as completed by vprimachenko** 2014-02-14 14:56 UTC
Labels: bug, st2
